//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1591

// Generated from: CommunityService.proto
// Note: requires additional types generated from: steammessages_unified_base.steamclient.proto
namespace SteamIrcBot
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CCommunity_GetPlayerCount_Request")]
  public partial class CCommunity_GetPlayerCount_Request : global::ProtoBuf.IExtensible
  {
    public CCommunity_GetPlayerCount_Request() {}
    
    private readonly global::System.Collections.Generic.List<uint> _appids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"appids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> appids
    {
      get { return _appids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CCommunity_GetPlayerCount_Response")]
  public partial class CCommunity_GetPlayerCount_Response : global::ProtoBuf.IExtensible
  {
    public CCommunity_GetPlayerCount_Response() {}
    
    private readonly global::System.Collections.Generic.List<CCommunity_GetPlayerCount_Response.AppPlayed> _apps_played = new global::System.Collections.Generic.List<CCommunity_GetPlayerCount_Response.AppPlayed>();
    [global::ProtoBuf.ProtoMember(1, Name=@"apps_played", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CCommunity_GetPlayerCount_Response.AppPlayed> apps_played
    {
      get { return _apps_played; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppPlayed")]
  public partial class AppPlayed : global::ProtoBuf.IExtensible
  {
    public AppPlayed() {}
    

    private uint _appid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"appid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint appid
    {
      get { return _appid; }
      set { _appid = value; }
    }

    private uint _players = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint players
    {
      get { return _players; }
      set { _players = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    public interface ICommunity
    {
      CCommunity_GetPlayerCount_Response GetPlayerCount(CCommunity_GetPlayerCount_Request request);
    
    }
    
    
}
#pragma warning restore 1591
